// <auto-generated />
using System;
using FitGoalAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitGoalAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.Ejercicios", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EjercicioId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoMuscular")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEjercicio")
                        .HasColumnType("longtext");

                    b.HasKey("EjercicioId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("Shared.Models.Entrenamientos", b =>
                {
                    b.Property<int>("EntrenamientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EntrenamientoId"));

                    b.Property<TimeSpan>("DuracionTotal")
                        .HasColumnType("time(6)");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("longtext");

                    b.HasKey("EntrenamientoId");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("Shared.Models.ProgresoUsuarios", b =>
                {
                    b.Property<int>("ProgresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgresoId"));

                    b.Property<float>("Brazo")
                        .HasColumnType("float");

                    b.Property<float>("Cintura")
                        .HasColumnType("float");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Pecho")
                        .HasColumnType("float");

                    b.Property<float>("Peso")
                        .HasColumnType("float");

                    b.Property<float>("Pierna")
                        .HasColumnType("float");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("longtext");

                    b.HasKey("ProgresoId");

                    b.ToTable("ProgresoUsuarios");
                });

            modelBuilder.Entity("Shared.Models.RutinaEjercicios", b =>
                {
                    b.Property<int>("RutinaEjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RutinaEjercicioId"));

                    b.Property<TimeSpan>("Descanso")
                        .HasColumnType("time(6)");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("int");

                    b.Property<int>("RutinaId")
                        .HasColumnType("int");

                    b.Property<int>("Series")
                        .HasColumnType("int");

                    b.HasKey("RutinaEjercicioId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("Shared.Models.Rutinas", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RutinaId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("DuracionTotal")
                        .HasColumnType("time(6)");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("longtext");

                    b.HasKey("RutinaId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("Shared.Models.Tips", b =>
                {
                    b.Property<int>("TipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TipId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("TipId");

                    b.ToTable("tips");
                });

            modelBuilder.Entity("Shared.Models.Usuarios", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<float>("AguaDiaria")
                        .HasColumnType("float");

                    b.Property<float>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .HasColumnType("longtext");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<float>("PesoActual")
                        .HasColumnType("float");

                    b.Property<float>("PesoIdeal")
                        .HasColumnType("float");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Shared.Models.RutinaEjercicios", b =>
                {
                    b.HasOne("Shared.Models.Rutinas", null)
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Rutinas", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
